### ISSUE TITLE
Android Tv Support

### ISSUE THREAD

**Issue by LeeRoyManea** [Admiral-Billy/Pokerogue-App#54]
It runs great on my android tv. Only 2 features are missing.  A launcher would be nice ( im am forced to start over installed apps) and  controller support for the loader screen.

**Comment by Admiral-Billy** [comment]
Oh yeah the controller support thing is fair. I'll see if it's not too bad to do and work it in at some point.

As for the launcher thing, are you referring to it not being considered a game for stuff like the Game Launcher, or something else?

**Comment by LeeRoyManea** [comment]
It just not shows up as a tv app. I think there have one or two variables to be set. Tv apps have some specific icon i think they appear as a reactangle with more width then height and not square.  I can start the app with a sideload launcher or go to the list of installed apps and open it from there. But is not appears on the "home" screen. For that reason i cant launch it normaly. No deal breaker but is unconvenient.

**Comment by LeeRoyManea** [comment]
If the controller thing is to time consuming i would love to see  some sort of auto boot as a replacement. If there are no activity for x seconds launch the last used option.

**Comment by Admiral-Billy** [comment]
Gotcha, I'll see what I can do next time i update the app.

**Comment by Admiral-Billy** [comment]
I think I've implemented this, so expect to see it in a day or two.

**Comment by ItsDeidara** [comment]
Sorry to respond to a closed issue, but I just tried out the new APK with this support. The app still does not appear in my app lists, even with a fresh install. On top of that, I am unable to login since the keyboard does not seem to function. Either with touch screen or the controller

(pics in album because github has a 10mb file limit)
https://imgur.com/a/7Ic0eQm

**Comment by Admiral-Billy** [comment]
Oh yeah, I forgot that part of the request. I just fixed it not showing up in the app list, but I can't seem to replicate the keyboard thing. On my android TV emulator at least, I can fully log in using a TV remote's controls (although it's a bit janky; you hit a button to make it pop up, then can enter your username, then have to hit next for password, and then next works for login; I have no idea if there's a way to register from the TV)

**Comment by LeeRoyManea** [comment]
On my TV everything works except of the app apearing in the app list. 
I can log in, everything with my remote. I could even play pokemon with the remote (if arrows and a key is enough). With the controller the cursor is not moving in the keyboard section (Login).  Everything else works great.

**Comment by LeeRoyManea** [comment]
Die apk from zips works for me thank you

**Comment by ItsDeidara** [comment]
Ironically I'm unable to install that debug APK. I get an "error parsing the package" when attempting to install the APK.

I've seen a few others reporting this error from installing the latest release apk as well in the offline-modding discord channel.

**Comment by ItsDeidara** [comment]
I can confirm that the app now appears on the homescreen, thank you! As for the keyboard what do you mean by remote? Unfortunately, I don't have access to another way to control the system to use the keyboard besides the touchscreen itself. Unless you mean another controller like a Bluetooth xbox controller? 

![IMG_0153](https://github.com/Admiral-Billy/Pokerogue-App/assets/16449821/5ec9539b-0604-4e91-ade3-23917673fa77)

**Comment by ItsDeidara** [comment]
So I actually found a bluetooth controller to try and connect(xbox one if it matters)  and that lets me somewhat use the keyboard for the sign in screen.

I can use the A button to select whatever is selected by default when the keyboard shows up(in this case Q), and also use B to erase whatever I just entered. However, I still can not scroll across the keyboard to select different letters.

Sorry for the spam, I figured this extra information could be useful!

**Comment by LeeRoyManea** [comment]
@ItsDeidara 

> I can confirm that the app now appears on the homescreen, thank you! As for the keyboard what do you mean by remote?

im using the nvidia shield. so i am using the nvidia shield remote.  i have also connected a xbox controller. 
the remote is not supporting to go back "press b" or going into the settings menu "start? / select?"
with the xbox controller i cant control the onscreen keyboard. this stuff i do with the nvidia shield remote. 

if you dont have a remote you may could connect a bluetooth keyboard?  for mouse control on tv i use "Bluetooth Keyboard & Mouse"  on my android phone.  For Keyboard you may have to pay. 

To be honest.  on the nvidia shield its a laggy experience.  i have a pc connected with chimeraos i mostly use (pokerouge win exe with proton). but i dont always to boot the pc to just play 15 minutes pokerouge.  so the nvidia shield works well for that situation. it only starts lagging after some time which i belive is maybe a ram issue caused by webkit?

**Comment by Odizinne** [comment]
I can confirm about the lag on nvidia Shield TV (pro 2019). I also tested building a minimal APK with only a webview, same experience.
